import type { Metadata } from 'next'
import { Suspense } from 'react'

import { HeaderCheckout } from '@/components'

export const metadata: Metadata = {
	title: 'Checkout',
	description: 'Generated by create next app'
}

export default function CheckOutLayout({ children }: { children: React.ReactNode }) {
	return (
		<main className='min-h-screen'>
			<Suspense>
				<HeaderCheckout />
			</Suspense>
			{children}
		</main>
	)
}
