import type { Metadata } from 'next'
import { Suspense } from 'react'

import { Layout } from '@/components/layout/Layout'

import { Container, Header } from '@/components'

export const metadata: Metadata = {
	title: 'Products',
	description: 'Generated by create next app'
}

export default function AdminLayout({ children }: { children: React.ReactNode }) {
	return (
		<main className='min-h-screen'>
			<Suspense>
				<Header hasSearch={true} />
			</Suspense>
			<Container>
				<Layout hasAdmin={true}>{children}</Layout>
			</Container>
		</main>
	)
}
