import type { Metadata } from 'next'
import { Suspense } from 'react'

import { Footer, Header, ScrollUp } from '@/components'

export const metadata: Metadata = {
	title: 'Products',
	description: 'Generated by create next app'
}

export default function ProductLayout({ children }: { children: React.ReactNode }) {
	return (
		<main className='min-h-screen'>
			<Suspense>
				<Header hasSearch={true} />
			</Suspense>
			{children}
			<Footer />
			<ScrollUp />
		</main>
	)
}
